/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIPackage;

import DataPackage.StudentClass;
import OperationsPackage.DivisionClass;
import OperationsPackage.PlaceClass;
import OperationsPackage.StandardsClass;
import OperationsPackage.StudentUpdateClass;
import OperationsPackage.StudentViewClass;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import student.repository.StudentRepository;

/**
 *
 * @author Nishil E
 */
public class StudentUpdation extends javax.swing.JFrame {
    StudentClass studentClass1;
    StudentClass studentClass2;
    StudentViewClass studentViewClass;
    ResultSet rs;
    /**
     * Creates new form StudentUpdateFrame
     */
    public StudentUpdation() {
        initComponents();
        regTextField.setEditable(false);//Code to make text box non-editable
         genderComboBox.removeAllItems();
             genderComboBox.addItem("Select");
             genderComboBox.addItem("Male");
             genderComboBox.addItem("Female");
             genderComboBox.addItem("Other");
        
         viewPlaces();// Function to view places
         viewClasses();// Function to view classes
         viewDivisions();// Function to view divisions 
        
        
        studentViewClass = new StudentViewClass();
        studentClass1 = new StudentClass();
        studentClass1 = studentViewClass.viewStudent(StudentRepository.ID);
        regTextField.setText(String.valueOf(StudentRepository.ID));
        nameTextField.setText(studentClass1.getStudentName());
        addressTextField.setText(studentClass1.getStudentAddress());
        pcntTextField.setText(String.valueOf(studentClass1.getStudentPercentage()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        genderComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        placeComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        classComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        divisionComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pcntTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        regTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Name of the student ");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Gender");

        placeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Address of the student");

        jLabel6.setText("Class");

        jLabel7.setText("Division");

        addressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextFieldActionPerformed(evt);
            }
        });

        classComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Place");

        divisionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Student Updation");

        jLabel2.setText("Register No.");

        pcntTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcntTextFieldActionPerformed(evt);
            }
        });

        jLabel9.setText("Percentage");

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9))
                                .addGap(151, 151, 151)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(regTextField)
                                    .addComponent(nameTextField)
                                    .addComponent(genderComboBox, 0, 247, Short.MAX_VALUE)
                                    .addComponent(placeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addressTextField)
                                    .addComponent(classComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(divisionComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pcntTextField)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateButton)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(regTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(placeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(addressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6))
                    .addComponent(classComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(divisionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(pcntTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(updateButton))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTextFieldActionPerformed

    private void pcntTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcntTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pcntTextFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        //Code to update students starts
        studentClass2  = new StudentClass();
        studentClass2.setRegN0(StudentRepository.ID);
         studentClass2.setStudentName(String.valueOf(nameTextField.getText()));
        studentClass2.setStudentGender(String.valueOf(genderComboBox.getSelectedItem()));
        studentClass2.setStudentAddress(String.valueOf(addressTextField.getText()));
        studentClass2.setStudentPlace(String.valueOf(placeComboBox.getSelectedItem()));
        studentClass2.setStudentClass(String.valueOf(classComboBox.getSelectedItem()));
        studentClass2.setStudentDivision(String.valueOf(divisionComboBox.getSelectedItem()));
        studentClass2.setStudentPercentage(Float.parseFloat(pcntTextField.getText()));
        //Code to update students ends
        StudentUpdateClass studentUpdateClass = new StudentUpdateClass();
        studentUpdateClass.updateStudent(studentClass2);
        StudenView homeFrame = new StudenView();
        homeFrame.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_updateButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        StudenView homeFrame = new StudenView();
        homeFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentUpdation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentUpdation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentUpdation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentUpdation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentUpdation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> classComboBox;
    private javax.swing.JComboBox<String> divisionComboBox;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField pcntTextField;
    private javax.swing.JComboBox<String> placeComboBox;
    private javax.swing.JTextField regTextField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
    
    //Function for view places in combo box starts
    private void viewPlaces() {
       try {
             
             placeComboBox.removeAllItems();
             placeComboBox.addItem("Select");
             PlaceClass placeClass = new PlaceClass();
             rs = placeClass.viewPlaces();
             while(rs.next()){
                 
                 placeComboBox.addItem(rs.getString("place_name"));
                 
             }} catch (SQLException ex) {
             Logger.getLogger(StudentRegistration.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
    //Function for view places in combo box ends
    
    //Function for view classes in combo box starts
     private void viewClasses() {
         try {
             classComboBox.removeAllItems();
             classComboBox.addItem("Select");
             StandardsClass standardsClass = new StandardsClass();
             rs = standardsClass.viewClasses();
             while(rs.next()){
                 classComboBox.addItem(rs.getString("class_name"));
             }
         } catch (SQLException ex) {
             Logger.getLogger(StudentRegistration.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
    //Function for view classes in combo box ends
     
     //Function for view divisions in combo box starts
    private void viewDivisions() {
         try {
             divisionComboBox.removeAllItems();
             divisionComboBox.addItem("Select");
             DivisionClass divisionClass = new DivisionClass();
             rs = divisionClass.viewDivisions();
             while(rs.next()){
                 divisionComboBox.addItem(rs.getString("division"));
             }
         } catch (SQLException ex) {
             Logger.getLogger(StudentRegistration.class.getName()).log(Level.SEVERE, null, ex);
         }
    }
    //Function for view divisions in combo box ends
}
